https://drive.google.com/file/d/1oBiV3zo3ONUYXX9sLvUjyKX7DgjQh493/edit

In [ ]:
!gdown --id 1oBiV3zo3ONUYXX9sLvUjyKX7DgjQh493

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1oBiV3zo3ONUYXX9sLvUjyKX7DgjQh493
To: /content/launch_test_task.csv
100% 127k/127k [00:00<00:00, 86.5MB/s]

In [ ]:
import pandas as pd
launch = pd.read_csv('/content/launch_test_task.csv', sep=';')
launch.head()

,user_id,session_id,region,platform,source
0,ce438bd29151e78bf09552d958737140,000da8f0-351a-40b4-9ffc-3b5708196f0c,Иркутск,2GIS 4 Android,android-app://com.google.android.ext.services
1,0ee0438b13fe6a3b0b95cd488f6ee1b7,00f9badc-1a72-4cf3-8640-c7e862038e39,Барнаул,2GIS 4 Android,android-app://com.whatsapp
2,ccb9a5426b6b76b948fb47e0a4b66725,00fdaeb5-fa6e-4da4-8e33-9df23af9664a,Нур-Султан,2GIS 4 Iphone,https://www.google.com
3,a1d16d7ff09a3d256d0a3442ea38f400,01464fac-ea44-413e-81fd-aece41b925e6,Комсомольск-на-Амуре,2GIS 4 Android,android-app://ru.dublgis.dgismobile
4,4f482f4dc1a2e02ddc9b7e7575f99a46,014dba73-473e-4b20-ad74-d233a57da9e5,Пермь,2GIS 4 Android,android-app://com.viber.voip

In [ ]:
print(f'Количество строк: {launch.shape[0]}')
print(f'Количество столбцов: {launch.shape[1]}')

Количество строк: 960
Количество столбцов: 5

In [ ]:
launch['platform'].value_counts()

platform
2GIS 4 Android    639
2GIS 4 Iphone     321
Name: count, dtype: int64

In [ ]:
launch['app_platform'] = launch['platform'].apply(
    lambda x: 'Android' if 'Android' in x else 'iOS'
)

grouped = (
    launch
    .groupby(['source', 'app_platform'])
    .agg(
        unique_users=('user_id', 'nunique'),
        sessions=('session_id', 'count')
    )
    .unstack(fill_value=0)
)

grouped.columns = [f'{metric}_{platform}'
                   for metric, platform in grouped.columns]

task1 = grouped.reset_index()
task1 = (
    task1
    .assign(total=task1['unique_users_Android'] + task1['unique_users_iOS'])
    .sort_values('total', ascending=False)
    .drop(columns='total')
)

task1.to_csv('task1_source_platform.csv', index=False)
task1.head(10)

,source,unique_users_Android,unique_users_iOS,sessions_Android,sessions_iOS
26,android-app://com.whatsapp,134,0,199,0
45,https://www.google.com,0,108,0,131
46,https://www.google.com/,0,90,0,123
34,android-app://ru.dublgis.dgismobile,75,0,80,0
49,https://yandex.ru/,0,30,0,41
29,android-app://com.yandex.browser,22,0,29,0
39,android-app://ru.yandex.searchplugin,18,0,25,0
27,android-app://com.whatsapp.w4b,18,0,29,0
40,android-app://sinet.startup.inDriver,15,0,63,0
23,android-app://com.taxsee.driver,13,0,47,0

In [ ]:
task2 = (
    launch
    .groupby('region')
    .agg(unique_users=('user_id', 'nunique'))
    .reset_index()
    .sort_values('unique_users', ascending=False)
    .rename(columns={'region': 'city'})
)

task2.to_csv('task2_users_by_city.csv', index=False)
task2.head(10)

           city  unique_users
3        Алматы            70
50   Нур-Султан            47
49  Новосибирск            35
11       Бишкек            30
41       Москва            19
86    Челябинск            18
77       Тюмень            18
33   Красноярск            17
21      Иркутск            14
32    Краснодар            12

In [ ]:
from google.colab import files
files.download('task1_source_platform.csv')
files.download('task2_users_by_city.csv')